version: '3.8'

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=passwordExample
      - MYSQL_DATABASE=nest
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

volumes: 
  db: